// Host-only oracle: execute the exact upstream module, never ship it in the APK.
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {execFileSync} from 'node:child_process';

const [beautyRoot, outputRoot, mode='fixtures'] = process.argv.slice(2);
const expected='34d0b6e04023c8ca4e7dd25b2381a2128f12c03a';
if (!beautyRoot || !outputRoot) throw Error('reference.mjs BEAUTY_CHECKOUT OUTPUT [data|fixtures]');
if (execFileSync('git',['-C',beautyRoot,'rev-parse','HEAD'],{encoding:'utf8'}).trim()!==expected)
  throw Error('Beauty reference revision mismatch');
if (execFileSync('git',['-C',beautyRoot,'status','--porcelain','--untracked-files=no'],{encoding:'utf8'}).trim())
  throw Error('Beauty reference checkout has tracked modifications');
const m=await import(pathToFileURL(path.resolve(beautyRoot,'examples/autogenerated/moving-face/model.mjs')));
const anatomy=m.compileAnatomy(m.readTable(fs.readFileSync(path.join(beautyRoot,'anatomy/musculature.tsv'),'utf8')));
const controls=m.readTable(fs.readFileSync(path.join(beautyRoot,'facial-mask/controls.csv'),'utf8'),',');
const mesh=m.createNeutralMesh();
if (controls.length!==36||anatomy.actuators.length!==102) throw Error('Unexpected reference interface');
fs.mkdirSync(outputRoot,{recursive:true});
const fields=['pull','skeletal','hyoid','none','bulge','cheek_compress','mentalis','lip_ring','lid_raise','lid_upper','lid_lower','eye_ring','modiolus'];
const v=p=>'{'+p.join(',')+'}';
if(mode==='data') {
  const rows=['/* Generated from Beauty '+expected+'; regenerate and compare in CI. */'];
  rows.push('const char *const face_control_names[FACE_CONTROLS] = {'+controls.map(r=>JSON.stringify(r.id)).join(',')+'};');
  rows.push('const char *const face_actuator_names[FACE_ACTUATORS] = {'+anatomy.actuators.map(a=>JSON.stringify(a.id)).join(',')+'};');
  rows.push('static const Actuator rest_actuators[FACE_ACTUATORS] = {');
  for(const a of anatomy.actuators) {
    if(!fields.includes(a.field)) throw Error('Unknown field '+a.field);
    const jawOrigin=['depressor_anguli_oris','depressor_labii_inferioris','mentalis','mylohyoid','geniohyoid','digastric_anterior'].includes(a.region_id);
    const jawInsertion=/^(masseter_|temporalis_|medial_pterygoid_|lateral_pterygoid_)/.test(a.region_id);
    const conditional=['digastric_anterior','mylohyoid','geniohyoid'].includes(a.region_id);
    rows.push('{'+[v(a.origin),v(a.insertion),v(a.radius),v(a.jaw),v(a.hyoid),fields.indexOf(a.field),a.side==='R'?-1:a.side==='L'?1:0,+jawOrigin,+jawInsertion,+conditional].join(',')+'},');
  }
  rows.push('};\nstatic const double control_gains[FACE_CONTROLS][FACE_ACTUATORS] = {');
  for(const c of controls) {
    const q=m.controlsToMuscles(anatomy,controls,{[c.id]:1});
    rows.push(v(anatomy.actuators.map(a=>q[a.id]))+',');
  }
  rows.push('};\nconst FacePoint face_rest_vertices[FACE_VERTICES] = {',...mesh.vertices.map(p=>v(p)+','),'};');
  rows.push('const unsigned short face_triangles[FACE_TRIANGLES][3] = {',...mesh.triangles.map(t=>v(t)+','),'};');
  rows.push('const unsigned short face_landmarks[FACE_LANDMARKS] = {'+Object.values(mesh.landmarks).join(',')+'};');
  rows.push('const char *const face_landmark_names[FACE_LANDMARKS] = {'+Object.keys(mesh.landmarks).map(k=>JSON.stringify(k)).join(',')+'};');
  rows.push('static const FacePoint rest_mandible[7] = {'+mesh.mandible.map(v).join(',')+'};');
  rows.push('static const FacePoint rest_hyoid[3] = {'+mesh.hyoid.map(v).join(',')+'};');
  fs.writeFileSync(path.join(outputRoot,'face_data.inc'),rows.join('\n')+'\n');
  fs.writeFileSync(path.join(outputRoot,'face_data_sizes.h'),`#define FACE_VERTICES ${mesh.vertices.length}\n#define FACE_TRIANGLES ${mesh.triangles.length}\n#define FACE_LANDMARKS ${Object.keys(mesh.landmarks).length}\n`);
} else if(mode==='fixtures') {
  const cases=[];
  const controlVector=values=>controls.map(c=>values[c.id]||0);
  for(const [name,values] of Object.entries(m.expressions)) cases.push([name,0,controlVector(values)]);
  for(let i=0;i<36;i++) for(const amount of [.25,1]) cases.push(['control_'+i+'_'+amount,0,controls.map((_,j)=>i===j?amount:0)]);
  cases.push(['all_controls',0,Array(36).fill(1)]);
  // Seeded dense combinations expose saturation, shared procerus and jaw suppression.
  let seed=817;
  for(let i=0;i<16;i++) cases.push(['combined_'+i,0,controls.map(()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;})]);
  for(let i=0;i<102;i++) cases.push(['actuator_'+i,1,anatomy.actuators.map((_,j)=>i===j?1:0)]);
  for(const [name,values] of Object.entries(m.activationExamples)) cases.push([name,1,anatomy.actuators.map(a=>values[a.id]||0)]);
  const inputs=[],results=[];
  for(const [name,kind,values] of cases) {
    const q=kind?Object.fromEntries(anatomy.actuators.map((a,i)=>[a.id,values[i]])):
      m.controlsToMuscles(anatomy,controls,Object.fromEntries(controls.map((c,i)=>[c.id,values[i]])));
    const r=m.deform(anatomy,mesh,q);
    const nums=[...anatomy.actuators.map(a=>r.q[a.id]),r.pose.opening,r.pose.protrusion,r.pose.excursion,r.pose.clench,...r.pose.hyoid,r.pose.fixation,
      ...r.junctions.L,...r.junctions.R,r.tissueScale,...r.vertices.flat(),...r.mandible.flat(),...r.hyoid.flat()];
    inputs.push([name,kind,...values].join('\t'));
    results.push([name,...nums].join('\t'));
  }
  fs.writeFileSync(path.join(outputRoot,'inputs.tsv'),inputs.join('\n')+'\n');
  fs.writeFileSync(path.join(outputRoot,'expected.tsv'),results.join('\n')+'\n');
  console.log('Beauty fixtures:',cases.length,'cases;',mesh.vertices.length,'vertices;',mesh.triangles.length,'triangles; all 102 actuators');
} else throw Error('Unknown mode');
